on:
  push:
    branches:
      - stage/*
    paths:
      - src/**

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo "Branch name is ${{ github.ref }}"
